### ISSUE TITLE
X-axis (build no) becomes very cluttered with a large amounts of builds.

### ISSUE THREAD

**Issue by AndersHoglund** [Praqma/memory-map-plugin#39]
X-axis (build no) becomes very cluttered with a large amounts of builds.
Sample usage here: http://andwho.sytes.net:8080/job/AndWho_Betaflight/
Or the the attached screen shot.

![bf_jenkins_memmap](https://user-images.githubusercontent.com/15121917/34954587-409b21e4-fa21-11e7-9649-07ace3193958.jpg)

**Comment by buep** [comment]
Hi @AndersHoglund we do not run into the issue because we do not save that many builds.

I'm suspecting that other graphing plugins, like the Warnings plugin will do the same?

If we should fix this, we should maybe only write the build number for every x build when the number of builds increases to a certain number.

Would that be a solution? Should it be configurable or just a fixed configuration we do it?

**Comment by AndersHoglund** [comment]
You need to able to see the long term trend on metrics like this. 
No other plugins I use shows this problem, examples here: 
http://andwho.sytes.net:8080/job/BorisB_BetaFlight/
In some way builds numbers are scaled and show only every 5th, 10th or 50th value, depending on total range of build numbers.

**Comment by AndersHoglund** [comment]
And of course it should be a dynamic scaling, no more config items please. And certainly not a fixed scaling.

**Comment by OEHC** [comment]
This issue should be fixed in commit 6351062

**Comment by AndersHoglund** [comment]
Thanks, pulled and built branch `39-x-axis-build-no-becomes-very-cluttered-with-a-large-amounts-of-builds` . Seems to work OK and fixes this issue.
![jenikins-bff3-memory-usage-fixed](https://user-images.githubusercontent.com/15121917/37358819-5002bc9e-26ec-11e8-8a99-ba101d6e7e47.jpg)
